### ISSUE TITLE
About the trainning

### ISSUE THREAD

**Issue by superhero-7** [crmauceri/ReferringExpressions#1]
I'd like know how much of the  final loss  value of the baseline model using refCOCOg dataset?And How much time dose the trainning take? 
I would appreciate your reply very much!

**Comment by crmauceri** [comment]
The average training loss for the last epoch was 18.66.

As far as training time, it will vary based on your GPUs. We were using an nvidia P6000 GPU. I don't remember the exact amount of time, but several days.
